server:
  port: 8091
  contextPath: /spring-cloud-sleuth-server

spring:
  application:
    name: spring-cloud-sleuth-server
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true


logging:
  level:
    root: info