server:
  port: 9411

spring:
  application:
    name: spring-cloud-sleuth-zipkin-server
  sleuth:
    enabled: false


logging:
  level:
    root: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug