server:
  port: 8095

spring:
  application:
    name: spring-cloud-sleuth-zipkin-server
  sleuth:
    enabled: false
  rabbitmq:
    host: 10.50.115.78
    port: 5672
    username: admin
    password: admin

###########storage to mysql##########
zipkin:
  storage:
    type: mysql
    mysql:
      host: 127.0.0.1
      port: 3306
      username: root
      password: 5805703
      db: zipkin
      maxActive: 10
      useSsl: false

logging:
  level:
    root: info
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: info